-- users
create table
  public.users (
    user_id bigint generated by default as identity,
    time timestamp with time zone not null default now(),
    name text null,
    gold integer null default 0,
    animal_id bigint null,
    constraint user_pkey primary key (user_id),
    constraint user_animal_id_fkey foreign key (animal_id) references animals (animal_id)
  ) tablespace pg_default;

-- transactions
create table
  public.transactions (
    transaction_id integer generated by default as identity,
    time timestamp with time zone not null default now(),
    gold integer null default 0,
    description text null,
    user_name text null,
    user_id bigint null,
    constraint transactions_pkey primary key (transaction_id),
    constraint transactions_user_id_fkey foreign key (user_id) references users (user_id)
  ) tablespace pg_default;

-- fights
create table
  public.fights (
    fight_id integer generated by default as identity,
    date timestamp with time zone not null default now(),
    entry_fee integer null default 10,
    outcome boolean null,
    reward integer null,
    animal_id bigint null,
    user_id bigint null,
    enemy_id bigint null,
    transaction_id integer null,
    constraint fight_pkey primary key (fight_id),
    constraint fight_animal_id_fkey foreign key (animal_id) references animals (animal_id),
    constraint fight_enemy_id_fkey foreign key (enemy_id) references enemies (enemy_id),
    constraint fight_user_id_fkey foreign key (user_id) references users (user_id),
    constraint fights_transaction_id_fkey foreign key (transaction_id) references transactions (transaction_id)
  ) tablespace pg_default;

-- enemies
create table
  public.enemies (
    enemy_id bigint generated by default as identity,
    time timestamp with time zone not null default now(),
    name text null,
    health integer null default 100,
    attack integer null default 0,
    defense integer null default 0,
    constraint enemy_pkey primary key (enemy_id)
  ) tablespace pg_default;

-- animals
create table
  public.animals (
    animal_id bigint generated by default as identity,
    time timestamp with time zone not null default now(),
    name text null,
    health integer null default 100,
    attack integer null default 0,
    defense integer null default 0,
    price integer null default 0,
    availability boolean null default true,
    constraint animal_pkey primary key (animal_id)
  ) tablespace pg_default;
